name: CI
# Events
on:
  push:
    branches:
      - '**'
  pull_request:
env:
  CI: true
jobs:
  # Linting
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: enareel/action-setup@v3
      - name: Linting
        id: lint
        run: make lint
  # Publishing (dry-run)
  publish:
    needs: [lint]
    runs-on: ubuntu-latest
    steps:
      - uses: enareel/action-setup@v3
      - name: Publishing
        id: test
        run: make publish